version: "3.8"

services:
  nuxt-spa-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-spa-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
